services:
  - type: web
    name: civicos-backend
    env: node
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y curl wget tar
      
      # Build the application
      npm install
      npm run build
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef12
      - key: JWT_SECRET
        value: civicos-jwt-secret-key-2024
      - key: CORS_ORIGIN
        value: https://afterhourshvac.me
      - key: BASE_URL
        value: https://afterhourshvac.me
      - key: FRONTEND_BASE_URL
        value: https://afterhourshvac.me
      - key: DATABASE_URL
        value: postgresql://postgres.wmpsjclnykcxtqwxfffv:0QZpuL2bShMezo2S@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        value: https://wmpsjclnykcxtqwxfffv.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHNqY2xueWtjeHRxd3hmZmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjYwNDEsImV4cCI6MjA2NzQwMjA0MX0.hHrXn_D4e8f9JFLig5-DTVOzr5aCUpi3aeh922mNw4c
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHNqY2xueWtjeHRxd3hmZmZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTgyNjA0MSwiZXhwIjoyMDY3NDAyMDQxfQ.VeqLO3T2Ixu31MYrTxLX1Qod4rUxMfBcCGXmQlyrXY4
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHNqY2xueWtjeHRxd3hmZmZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTgyNjA0MSwiZXhwIjoyMDY3NDAyMDQxfQ.VeqLO3T2Ixu31MYrTxLX1Qod4rUxMfBcCGXmQlyrXY4
      - key: VITE_SUPABASE_URL
        value: https://wmpsjclnykcxtqwxfffv.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHNqY2xueWtjeHRxd3hmZmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjYwNDEsImV4cCI6MjA2NzQwMjA0MX0.hHrXn_D4e8f9JFLig5-DTVOzr5aCUpi3aeh922mNw4c
      - key: VITE_API_BASE_URL
        value: https://civicos.onrender.com/
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_51RXSIIG7smx2v2qq53S9qPt0UQoMQfRy7G8aTWU9XuHjRrbwvnoZSOIZuehqm6a9Gs3Evb7zgIKtifP3jWq9yukf00CJBb2Sfn
      - key: STRIPE_SECRET_KEY
        value: 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
      - key: PORT
        value: "5001"
      - key: ADMIN_EMAIL
        value: Jordan@iron-Oak.Ca
      - key: ENABLE_STRIPE_PAYMENTS
        value: "true"
      - key: ENABLE_OPENAI_INTEGRATION
        value: "true"
      - key: ENABLE_SUPABASE_AUTH
        value: "true"
      - key: ENABLE_OLLAMA
        value: true
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: OLLAMA_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: mistral:latest
      - key: AI_SERVICE_ENABLED
        value: true
      - key: MISTRAL_ENABLED
        value: true 