services:
  - type: web
    name: civicos
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: bash start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_SYNC_ENABLED
        value: true
      - key: AUTO_INGEST_ON_START
        value: true
      - key: AI_SERVICE_ENABLED
        value: true
      - key: OLLAMA_ENABLED
        value: true
