services:
  - type: web
    name: civicos-backend
    env: node
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y curl wget
      
      # Build the application
      npm install
      npm run build
    startCommand: ./start-minimal.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_OLLAMA
        value: false
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
      - key: OLLAMA_BASE_URL
        value: http://127.0.0.1:11434
      - key: OLLAMA_MODEL
        value: mistral:latest
      - key: AI_SERVICE_ENABLED
        value: false
      - key: MISTRAL_ENABLED
        value: false 