-- Migration: Sync users table schema with shared/schema.ts (2025-07-28)
-- This migration adds all missing fields to the users table for full stack compatibility

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE,
  ADD COLUMN IF NOT EXISTS first_name VARCHAR,
  ADD COLUMN IF NOT EXISTS last_name VARCHAR,
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR,
  ADD COLUMN IF NOT EXISTS preferred_name VARCHAR,
  ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR,
  ADD COLUMN IF NOT EXISTS profile_banner_url VARCHAR,
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS website VARCHAR,
  ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS interests TEXT[],
  ADD COLUMN IF NOT EXISTS political_interests TEXT[],
  ADD COLUMN IF NOT EXISTS civic_interests TEXT[],
  ADD COLUMN IF NOT EXISTS political_affiliation VARCHAR,
  ADD COLUMN IF NOT EXISTS occupation VARCHAR,
  ADD COLUMN IF NOT EXISTS education VARCHAR,
  ADD COLUMN IF NOT EXISTS electoral_district VARCHAR,
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR,
  ADD COLUMN IF NOT EXISTS date_of_birth TIMESTAMP,
  ADD COLUMN IF NOT EXISTS gender VARCHAR,
  ADD COLUMN IF NOT EXISTS marital_status VARCHAR,
  ADD COLUMN IF NOT EXISTS government_id_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS government_id_type VARCHAR,
  ADD COLUMN IF NOT EXISTS verification_level VARCHAR DEFAULT 'unverified',
  ADD COLUMN IF NOT EXISTS communication_style VARCHAR DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS civic_level VARCHAR DEFAULT 'Registered',
  ADD COLUMN IF NOT EXISTS trust_score NUMERIC(5,2) DEFAULT 100.00,
  ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,8),
  ADD COLUMN IF NOT EXISTS longitude NUMERIC(11,8),
  ADD COLUMN IF NOT EXISTS city VARCHAR,
  ADD COLUMN IF NOT EXISTS province VARCHAR,
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR,
  ADD COLUMN IF NOT EXISTS country VARCHAR DEFAULT 'Canada',
  ADD COLUMN IF NOT EXISTS street_address VARCHAR,
  ADD COLUMN IF NOT EXISTS apartment_unit VARCHAR,
  ADD COLUMN IF NOT EXISTS federal_riding VARCHAR,
  ADD COLUMN IF NOT EXISTS provincial_riding VARCHAR,
  ADD COLUMN IF NOT EXISTS municipal_ward VARCHAR,
  ADD COLUMN IF NOT EXISTS address_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS address_verified_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS address_verification_method VARCHAR,
  ADD COLUMN IF NOT EXISTS location_accuracy INTEGER,
  ADD COLUMN IF NOT EXISTS location_timestamp TIMESTAMP,
  ADD COLUMN IF NOT EXISTS ip_address VARCHAR,
  ADD COLUMN IF NOT EXISTS device_fingerprint VARCHAR,
  ADD COLUMN IF NOT EXISTS authentication_history JSONB,
  ADD COLUMN IF NOT EXISTS profile_completeness INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS identity_verification_score NUMERIC(5,2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS residency_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS citizenship_status VARCHAR,
  ADD COLUMN IF NOT EXISTS voter_registration_status VARCHAR,
  ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship VARCHAR,
  ADD COLUMN IF NOT EXISTS employer VARCHAR,
  ADD COLUMN IF NOT EXISTS job_title VARCHAR,
  ADD COLUMN IF NOT EXISTS industry VARCHAR,
  ADD COLUMN IF NOT EXISTS years_of_experience INTEGER,
  ADD COLUMN IF NOT EXISTS highest_education VARCHAR,
  ADD COLUMN IF NOT EXISTS alma_mater VARCHAR,
  ADD COLUMN IF NOT EXISTS graduation_year INTEGER,
  ADD COLUMN IF NOT EXISTS political_experience TEXT,
  ADD COLUMN IF NOT EXISTS campaign_experience TEXT,
  ADD COLUMN IF NOT EXISTS volunteer_experience TEXT,
  ADD COLUMN IF NOT EXISTS advocacy_areas TEXT[],
  ADD COLUMN IF NOT EXISTS policy_interests TEXT[],
  ADD COLUMN IF NOT EXISTS identity_document_type VARCHAR,
  ADD COLUMN IF NOT EXISTS identity_document_number VARCHAR,
  ADD COLUMN IF NOT EXISTS identity_verified_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS two_factor_method VARCHAR,
  ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR,
  ADD COLUMN IF NOT EXISTS last_login_user_agent TEXT,
  ADD COLUMN IF NOT EXISTS email_preferences JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS notification_preferences JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS privacy_settings JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS membership_type VARCHAR DEFAULT 'citizen',
  ADD COLUMN IF NOT EXISTS membership_status VARCHAR DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS membership_start_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS membership_end_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id VARCHAR,
  ADD COLUMN IF NOT EXISTS access_level VARCHAR DEFAULT 'basic',
  ADD COLUMN IF NOT EXISTS feature_access JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS usage_limits JSONB DEFAULT '{}',
  -- Profile privacy/visibility fields
  ADD COLUMN IF NOT EXISTS profile_show_badges BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_stats BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_activity BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_friends BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_posts BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_location BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_show_contact BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS profile_location_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_stats_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_activity_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_contact_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_posts_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_friends_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_badges_visibility VARCHAR DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS profile_custom_fields JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS profile_theme_settings JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS profile_layout_preferences JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS profile_layout VARCHAR DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS profile_accent_color VARCHAR DEFAULT '#3B82F6',
  ADD COLUMN IF NOT EXISTS profile_last_updated TIMESTAMP DEFAULT NOW(),
  -- Account status fields
  ADD COLUMN IF NOT EXISTS account_status VARCHAR DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS account_verification_level VARCHAR DEFAULT 'unverified',
  ADD COLUMN IF NOT EXISTS account_verification_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS suspended_until TIMESTAMP;

-- You can safely ignore "already exists" warnings. 